### ISSUE TITLE
GAISE entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#16]
Needs to be done: @nicholasjhorton on the case.

**Comment by nicholasjhorton** [comment]
My goal is to draft this today: sorry for letting this lag.

**Comment by hglanz** [comment]
I made a small change or two, in language only I think. I tried to make your list contain a sub-list, but it didn't come out. We can change it back. Otherwise, I like the post @nicholasjhorton 

I realize that it might have been good (at least for me) to discuss how we're writing these posts. Because there's no particular author identified on the posts themselves I've aimed for using a collective "we" if I use first person at all, in my posts. 

I missed it in our already live posts, but how do you both feel about using "I" and "my"? Of course I see now that you both have used them, but it still might be good for consistency across posts to establish some pseudo-formal practice for our posts going forward. What do you think? Sorry if we did discuss this and I'm forgetting...

**Comment by hardin47** [comment]
(I/we discussion for next week ...  I don't have strong opinions)

I made a few edits to the GAISE report (mostly slight wording changes).  I do hav a few more thoughts about other aspects, but i have to run to lunch...

**Comment by nicholasjhorton** [comment]
Ready for final review.

**Comment by hardin47** [comment]
i know that you just closed this, but i did want to add two more cents.  (feel free to ignore, i understand that i missed my window to comment).

the thing i wanted to say is that the GAISE entry might give us an opportunity to mention some of the things that we've heard from people wondering about "statistics" vs "data science".  or concerns about working with data technology without thinking carefully about where the data come from.

i was thinking something along the lines of *mentioning* some of the _other_ main GAISE guidelines and then saying that we believe in the foundations of the GAISE guidelines, and our focus on technology is not meant to indicate that technology is a replacement for an understanding of what claims are appropriate for a given analysis.  the items i'm thinking of include:

* confounding (yes, you did this, yay!)
* prediction models only predict values represented by the data which built the model
* issues with convenience (sometimes observational) data in general , scraping data
* there is a time and place for exploratory analysis and for inferential analysis, we should be very clear about what we want / why

so there you go.  i'm fine if you don't want to bring up the issues or don't feel like they are relevant to the flow of the blog post.  i'd just like a place to point people to that says "see, we *do* care about foundational statistical ideas.  look at our post and explore the GAISE guidelines more."

sorry to be so slow getting this to you.
