### ISSUE TITLE
tidyverse entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#18]

**Comment by nicholasjhorton** [comment]
Useful resources might include:

http://varianceexplained.org/r/teach-tidyverse/

https://rviews.rstudio.com/2017/06/08/what-is-the-tidyverse/

https://www.rstudio.com/resources/videos/data-science-in-the-tidyverse/

**Comment by nicholasjhorton** [comment]
Any updates on this front?  I'm teaching all day Friday and Saturday so it would be helpful if I could review sometime tomorrow.  Thanks in advance, Nick

**Comment by hglanz** [comment]
This post is ready for review by @nicholasjhorton @hardin47 Thanks!

**Comment by nicholasjhorton** [comment]
@hglanz I think that this is off to a good start.  Some comments:

1. I know they use "manipulation" to describe data wrangling.  I think that this is a mistake, given the pejorative meaning of "manipulation".  I would suggest noting this somewhere or making the shift.

2. It would be cool to include the figure with the tidyverse superimposed on the data analysis cycle graph. 

3. Two things are conflated here: the tidyverse and ggplot2.  Note that the syntax is all messed up (Hadley has admitted this) for ggplot2.  So the + and %>% mean different things.  PITA.  I wonder whether or not you can think of an example that's complicated to do using base R in terms of data wrangling, then provide a comparison of how that works in the tidyverse.  A combination of select, filter, group_by(), and summarize() perhaps?  You could then show a glimpse of the original data then the results.  I'd suggest also doing the equivalent in base R to point out how idiosyncratic that is.

4. This is also the place to introduce piping.  In retrospect @hardin47 should have done it for ingesting data but the tidyverse entry is probably a better place.

5. Hadley is moving away from "reshape()" and "gather()" as I understand.  Is this the time to jump to the new idioms?

Please let me know if it would be useful to talk as the clock is ticking for this entry.

**Comment by nicholasjhorton** [comment]
I had some other thoughts.  Can there be more focus on pedagogy?  What's been hard (or not) in teaching students to use dplyr for data wrangling?  Is it much simpler than base R because it is consistent?  Is it simple for students to grok piping?  My answer to the las two is yes.  

For ggplot2 I'm pretty conflicted.  I don't think that it's ideal for teaching purposes.  What it has is:

1. higher quality graphics than base graphics, for similar effort, and
2. all the cool kids use it so you can google

The additional learning outcomes (aes()?  +?  geom()?) require more effort in my experience.  We can get away with it at Cal Poly, Pomona, or Amherst but that may not be the case at other institutions.

I wonder about focusing on dplyr rather than ggplot2.

**Comment by hardin47** [comment]
if you are looking for more dplyr examples, you could use any of these:

https://github.com/dtkaplan/CVC/tree/gh-pages/Summer2016/Learn/Wrangling 

(From CVC workshop)

**Comment by hardin47** [comment]
1. I sort of agree with Nick about ggplot.  It has the "+" problem, and it also requires a lot more detail to explain it (and I think we are doing a ggplot blog later?).

One thing I really like about ggplot with the iris data is the use of `gather`.  I actually don't care that Hadley is going to change the word becauseI think you should teach the word as it is in the package, and recognize that some people will have to adjust along the way to keep up with how the packages / functions change.  

2. Is there a good `gather` example that doesn't involve ggplot?

3. I agree that we should emphasize that the tidyverse is actually EASIER for students than base R.  It's the profs who have a hard time switching over (the students don't have to switch over, they just learn a much more intuitive platform to start with).  Maybe we can advise them to just DO IT, and their students will pick it up.  Or the TAs can help.  Or something. 

4.  I agree that we should introduce the pipe here.   From: https://github.com/dtkaplan/CVC/blob/gh-pages/Summer2016/Learn/Parts_of_speech/R-command-structure.Rmd



## Command chains

Your commands will be written as chains.  

* Each link in the chain will be a data verb and its arguments.
    - The very first link is usually a data frame.
    
* Links are connected by the chaining symbol `%>%`

* Often, but not always, you will save the output of the chain in a named object.
    - This is done with the *assignment operator*, `<-`
```
    Name_of_result <-     
      Starting_data_frame  %>%    
      first verb (arguments for details) %>%   
      next verb (and its arguments) %>%    
           ... and so on, up through ...   
      last verb (and its arguments)  
```

## An example command chain

```{r}
Princes <- 
  BabyNames %>%
  filter(grepl("Prince", name)) %>%
  group_by(year) %>%
  summarise(total = sum(count))
```

* A good idea to put each link on its own line
* Note that `%>%` is at the end of each line.
    - Except ... `Princes <-` is assignment
    - Except ... The last line has no `%>%`.

**Comment by hglanz** [comment]
Thank you both for the rich comments. I'm very excited by this post, but I don't want to lose the forest through the trees here. We intended the posts to be concise introductions with links/paths to more. 

How much of an introduction to the pipe do you have in mind? Could this just be a couple sentences and a link? Same question goes for ggplot2.

Responses to @nicholasjhorton points on 5/30 at 2:32 PDT:

1. I agree about "manipulation" and have changed all occurrences to "wrangling".

2. I've changed the image, but I'm actually not sure exactly which picture you have in mind. Please advise.

3. I agree that the + and %>% are messed up, but ggplot2 is a pretty well defined piece of the tidyverse at this point. Hadley has admitted that the syntax is messed up, BUT he has also thoroughly explained why it would be a bad idea to write ggplot3 as an updated ggplot2 that uses %>% instead of +. So, while things could have been written/developed better from the beginning it doesn't seem like they're in a place right now worth changing. So, my vote is still to include ggplot2 in the tidyverse discussion. However, with ggplot2 on the list of "possible" topics I refer you back to my question about how much this tidyverse post should actually cover. It has the potential to be super high level and my inclination is in this direction, but I want there to be consensus among us. While there is more to explain with ggplot2, I thought David Robinson also encouraged teaching it to students first...and I think I agree. Even with more to explain, I like it better than base plotting. It reads better and is more consistent, I think.

4. This is my question about depth and coverage of this post (and posts in general).

5. I'm with @hardin47 here. I like the use of gather() and the point is not lost if this is becoming a (slightly) differently named function, so I'm in favor of keeping it for now.

@hardin47 I think the gather example with the iris data doesn't have to use ggplot. It could just be for computing summary statistics in a different format, right?

iris %>%
  gather(key = "flower_att", value = "measurement", Petal.Length, Petal.Width, Sepal.Length, Sepal.Width) %>%
  group_by(flower_att) %>%
  summarize(Mean = mean(measurement),
            SD = sd(measurement))

This is actually the format that some science journals prefer, but of course this isn't the only way to get to this format.

Re: tidyverse is easier for students. I thought David Robinson's post does a good job about this and summarizing it here was good. What else did you two have in mind to include here and emphasize on this item?

I know this is a long response, but I agree that this is a very rich entry and I'm excited to do it well. I think with resolution on these items I'll be confident about revising. I look forward to hearing back. Thanks so much.

**Comment by nicholasjhorton** [comment]
On May 31, 2019, at 3:29 AM, Hunter Glanz <notifications@github.com> wrote:

Thank you both for the rich comments. I'm very excited by this post, but I don't want to lose the forest through the trees here. We intended the posts to be concise introductions with links/paths to more.

How much of an introduction to the pipe do you have in mind? Could this just be a couple sentences and a link? Same question goes for ggplot2.

MY RESPONSE: I was thinking a sentence and a link.

Responses to @nicholasjhorton points on 5/30 at 2:32 PDT:

	• I agree about "manipulation" and have changed all occurrences to "wrangling".

MY RESPONSE: Thanks!

	• I've changed the image, but I'm actually not sure exactly which picture you have in mind. Please advise.

MY RESPONSE: Looks good.

	• I agree that the + and %>% are messed up, but ggplot2 is a pretty well defined piece of the tidyverse at this point. Hadley has admitted that the syntax is messed up, BUT he has also thoroughly explained why it would be a bad idea to write ggplot3 as an updated ggplot2 that uses %>% instead of +. So, while things could have been written/developed better from the beginning it doesn't seem like they're in a place right now worth changing. So, my vote is still to include ggplot2 in the tidyverse discussion. However, with ggplot2 on the list of "possible" topics I refer you back to my question about how much this tidyverse post should actually cover. It has the potential to be super high level and my inclination is in this direction, but I want there to be consensus among us. While there is more to explain with ggplot2, I thought David Robinson also encouraged teaching it to students first...and I think I agree. Even with more to explain, I like it better than base plotting. It reads better and is more consistent, I think.

MY RESPONSE: I have no problems with ggplot2: I think that should be our default for visualizations.  I just find it jarring and unhelpful to lump it in with the tidyverse.  The only connection I see is that you need tidy data to use ggplot2!

	• This is my question about depth and coverage of this post (and posts in general).

	• I'm with @hardin47 here. I like the use of gather() and the point is not lost if this is becoming a (slightly) differently named function, so I'm in favor of keeping it for now.

MY RESPONSE:I withdraw my suggestion.  

@hardin47 I think the gather example with the iris data doesn't have to use ggplot. It could just be for computing summary statistics in a different format, right?

iris %>%
gather(key = "flower_att", value = "measurement", Petal.Length, Petal.Width, Sepal.Length, Sepal.Width) %>%
group_by(flower_att) %>%
summarize(Mean = mean(measurement),
SD = sd(measurement))

This is actually the format that some science journals prefer, but of course this isn't the only way to get to this format.

Re: tidyverse is easier for students. I thought David Robinson's post does a good job about this and summarizing it here was good. What else did you two have in mind to include here and emphasize on this item?

MY RESPONSE: I'm thinking a few sentences from your (or our) experiences teaching dplyr and friends.

I know this is a long response, but I agree that this is a very rich entry and I'm excited to do it well. I think with resolution on these items I'll be confident about revising. I look forward to hearing back. Thanks so much.

MY RESPONSE: The long response was enormously helpful: I think that we're making great progress.

One other query: we talk about investing 20-30 minutes for someone reading the post.  What should they do to engage?  Is there a learnr tutorial they could explore?  Or should they just read David Robinson's blog?  (In retrospect I wonder if we should have guided readers to create their own R Markdown example using "New File" "R Markdown").

**Comment by hardin47** [comment]
Seems like we have a consensus for this post (thanks for all the back and forth, Hunter!).  I like all the responses above.  And I like this use case:

```
iris %>%
gather(key = "flower_att", value = "measurement", Petal.Length, Petal.Width, Sepal.Length, Sepal.Width) %>%
group_by(flower_att) %>%
summarize(Mean = mean(measurement), SD = sd(measurement))
```

If you know of `learnr` tutorials, I'd love to see them!  I don't have good resources to show my own students.  Maybe that is next summer's project.

**Comment by hglanz** [comment]
Thank you both! I'll make the revisions as soon as I can. Do we have a formal policy on revising old posts? Of course I don't want to completely rewrite anything, but I'm somewhat in favor of adding the short little R Markdown example to the R Markdown post, that Nick mentioned. 

Maybe just announce it to the google group?

**Comment by hardin47** [comment]
my personal view is that we should just update the posts when we want to.  and we shouldn't worry about telling people that we re-did it.  of course, the google format is a convenient way to tell them if we want to (we can "reply" to the original post on R Markdown).

But regardless of whether we tell people, we should definitely feel free to update the posts even after they are announced.

**Comment by hglanz** [comment]
Sorry to belabor things a bit.....what level of coverage should ggplot have in this post? I realize I didn't really get a clear picture from our exchange. 

learnr tutorials sound awesome, @hardin47 !

**Comment by hardin47** [comment]
my answer is: zero ggplot in this blog.  i think that is @nicholasjhorton 's view as well.  however, i have no need to tell you how to write the blog, and if you think ggplot helps tell your story better, i'm totally fine with you keeping it in.

**Comment by nicholasjhorton** [comment]
I would not object to the ggplot() calls you had.  My preference, however, would be to separate the tidying from the plotting.  (Alternatively, moving away from the plots would work for me as well.)

**Comment by nicholasjhorton** [comment]
This looks great.  See minor comments via https://github.com/hglanz/DS-Blog-Ex/commit/c60173afb1bc36dd6885185235ff3d4fe88c1a07

**Comment by hardin47** [comment]
I also made a few minor tweaks.  LOVE the iris comparison to base R.  

my only real comment is that it seems to need a sentence (or something, i'm not sure what the flow is supposed to be) **right before the side-by-side boxplots**.  maybe just specifying "there is so much more to learn in this arena, for example, see future blog posts exploring tidyverse plotting with ggplot2."

we might even give the URL because we do know what the URL will be, even though it isn't live yet.  what do you think?  

either way, i'm totally fine with this post as is.  you do whatever you think is best.

**Comment by hglanz** [comment]
Alrighty, "big" update. Thank you both for your edits. I added a sentence about the pipe and the link that @hardin47  provided. I also removed the plots, and just stuck with basically examples of the 5 main dplyr verbs.

I'm checking the box, but let me know if you have other comments or anything and I can make changes.
