### ISSUE TITLE
review of draft outreach and paragraph

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#20]
I've stubbed out a draft outreach piece. Comments and suggestions welcomed:

https://github.com/hglanz/DS-Blog-Ex/wiki/draft-of-outreach-email-and-paragraph-at-the-end-of-every-entry-(but-the-first)

Please let me know if this is not what you had in mind.

**Comment by hglanz** [comment]
Missing word in the following paragraph, second sentence?

_There is definitely an art to googling well that not everyone (including the three of us) can master. The data science field is also moving quickly, so answers from useful sites such as may be quickly out of date. Our ambition is that by reading the short overview entries, a variety of instructors will take the opportunity to learn more about the exciting developments in data science and statistics._

Otherwise, everything looks great!

**Comment by nicholasjhorton** [comment]
Fixed.  @hardin47 any final comments?

**Comment by hardin47** [comment]
1. I added "summer of 2019" to "summer".  

2. Also, the last sentence is "fast moving landscape of data science computation".  what do you think of just  "fast moving landscape of data science."  it isn't just computation ...  for example, ethics.  right?

(I'm going to make the change, but feel free to put it back.)

**Comment by nicholasjhorton** [comment]
Both changes look great to me.  

I'll work on adding this to the existing entries (then close this issue).

**Comment by nicholasjhorton** [comment]
I've added this to the existing entries and will close the issue.  I'd suggest using one of the existing entries as a starting point for new entries.
