### ISSUE TITLE
general UseR entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#58]
Can we each include some of our favorite talks that are available online, and elaborate on one or two (like @hardin47 did for the podcast entry?

**Comment by hardin47** [comment]
This was a really hard task!!!  First of all, watching videos takes forever.  I think #1 and #5 are the only two that I had watched before (I saw Hadley in person, and Jenny's I watched last summer after all the social media buzz).  

But the other hard thing is that all the big name people (whose talks I'd naturally be drawn to) are mostly white men.  And I think we should try to highlight a few women or data scientists of color.   I struggled a bit to find talks from that group that are general audience / impactful.   What do you think? Anyone come to mind of people we should highlight?

***1.  useR! 2016 https://channel9.msdn.com/events/useR-international-R-User-conference/useR2016/Towards-a-grammar-of-interactive-graphics?term=wickham&lang-en=true

hadley's "toward a grammar of interactive graphics"  useR 2016 at Stanford, he talks about list columns and it's the first time `tidyverse` is used (previously people had been calling it the hadleyverse).  44:10

he also introduced the piping with the little bunny foo foo example (34:00)

2. R Ladies global: useR! 2017 https://channel9.msdn.com/Events/useR-international-R-User-conferences/useR-International-R-User-2017-Conference/R-Ladies-Global-Community

always good to highlight what they are doing!  i wonder if they give statistics.  maybe there is also a 2018 talk?

3. Max Humber useR! 2017 scraping data with `rvest` and `purrr`  https://channel9.msdn.com/Events/useR-international-R-User-conferences/useR-International-R-User-2017-Conference/Scraping-data-with-rvest-and-purrr

these are great tools.  i wasn't that taken by the example, but ...

4. Roger Peng, useR! 2018 Teaching R to New Users: From tapply to Tidyverse https://www.youtube.com/watch?v=5033jBHFiHE 



*****5. Jenny Bryan, useR! 2018 Code Smells and Feels https://www.youtube.com/watch?v=7oyiPBjLAWY

CODE SMELLS!!!  Jenny Bryan is a genius.

6.  Sam Brilleman useR! 2018 simsurv: A Package for Simulating Simple or Complex Survival Data https://www.youtube.com/watch?v=fJTYsncvpvI

i like this talk because i teach survival analysis, and simulation is always good for educational setting.  it's hard to come up with realistic ways to simulate data in the survival setting

7. Elizabeth Stark useR! 2018 Production-ready R: Getting started with R and docker https://www.youtube.com/watch?v=lfG8cTqRRNA

i'm still wrapping my head around docker.  but it seems like something we should all be doing.  it's like the cloud, but you don't have to get your IT person to set up the server.

**Comment by hardin47** [comment]
also, we should definitely point out that UseR! 2019 starts on July 9, 2019.  http://www.user2019.fr/

And we should also tell people to follow the hashtag #useR2019

**Comment by hardin47** [comment]
from mine centinkaya-rundel ...

I don't know the work of all the keynote speakers but I happen to know what Joe Cheng is working on, I think it'll be a very cool talk. Also, Julien Cornebise is potentially not a very common household name in #rstats but his work is very cool. I'm also pretty sure Julia Stewart Lowndes' talk will be very interesting.

There's an education session, one of the talks that I'm looking forward to there is Mathematical Modeling in R, it's about HS Math courses. I don't hear much from that crowd in R contexts, so I think it'll be interesting.

There's also a reproducibility session, talks like Rmd first method seem interesting.

There's a talk on the polite package I want to see.

Angela Li is talking about teaching reproducible spatial analysis…

A talk on grammatical gener prediction of German nouns is interesting to me because I'm fascinated by gendered noun languages (and how difficult it is to learn them).

Jenny's usethis talk will be great I'm sure. I've been using that package a lot lately.

Francois from the Carpentries will be talking about how they use R in their daily operations that I want to see.

Kelly from RStudio will be talkin Advanced Git.

And Max Held will be talking about GitHub actions -- I'm very much looking forward to Max's work because I want to make updates to ghclass for auto feedback basead on that.

And I'm sure Hadley's talk will be great as usual :)

Best,
Mine

**Comment by nicholasjhorton** [comment]
Is there a draft of this available for review?

**Comment by hardin47** [comment]
ok, a useR draft is up!!!  hope it doesn't need too much work / editing, as I know it's supposed to go live on Tuesday.  Tuesday is the first day of the conference, and the keynotes are livestreamed.  the first keynote is at 10am which is 1am in Los Angeles.  i am thinking I might tweet about it on monday night.  what do you think?

thanks for the quick feedback @nicholasjhorton and @hglanz !!!

**Comment by nicholasjhorton** [comment]
The entry looks great: thanks for your work on this front.  I fixed two typos but didn't build.

Nick
