### ISSUE TITLE
pandas

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#67]
replicate multiple regression example from https::/teachdatascience.com/gaise in Python?

**Comment by hardin47** [comment]
@hglanz   have you made any progress on the pandas entry?  i was sort of waiting to look at it and then finish up reticulate.  let me know where you are in the process.  thanks!

**Comment by hglanz** [comment]
draft of pandas post is up on staging site now. @nicholasjhorton pandas doesn't really add regression and very many other stats tools besides aggregations and computation of some statistics, so for now I haven't included those types of examples.

I added one more example on top of what @hardin47 had done in the reticulate entry. I'm happy to add more example to the pandas post if you both think it would be good. I've linked to some good tutorials, so perhaps we could pick more from those to just include in the entry? One of them even uses the flights data (perhaps this is where you got the idea @hardin47 ....not sure).

**Comment by hardin47** [comment]
1.  Can you mention a bit about the structure of how it works?  That is, the whole "data.function" format ?  Seems like a Python thing, but I wonder if you could help walk the reader through the basics of the uses?

2. I'm having trouble with the link you gave to the pandas cheat sheet:  
http://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

i don't know what's up, but it's making my searching go wonky (google now won't let me search for anything).  does that link do anything odd for you?

3.  Do you want to add this link?  https://towardsdatascience.com/a-quick-introduction-to-the-pandas-python-library-f1b678f34673

4. You mention my post, but I thought we were going to switch order?  maybe @nicholasjhorton can decide which blog entry should go first?

5.  where you say "straight from the homepage..."  are you quoting something?  If so, I think it should be more obvious which of the words are quoted (either use quotations or block off the whole thing).

**Comment by hglanz** [comment]
@hardin47 

1. I've added some language to explain more about methods, but it's still a little general because they don't have to necessarily be "data.function" as opposed to "object.function". Let me know if I should add or change to specifics about the example or data/stats.

2. I've changed the link to one of the file on github. This seems to work better, but Kelly has told me that github links are not necessarily as permanent as I might like. If either of you have a better idea or can find it somewhere else let me know.

3. I've added that link to the Learn More. Thanks!

4. Yes, @nicholasjhorton care to weigh in here?

5. I've added quotations.

Thanks for the feedback. Keep it coming :)

**Comment by nicholasjhorton** [comment]
I think that this post should include the code in a copyable format (at present everything is just provided in images).  

Is this the entry where the parallel Python and R code would be displayed?  Or is that reticulate?

I wonder if a read through this from a pedagogical standpoint would be helpful.  I'm thinking of an instructor who has used R, knows a wee bit about python, but hasn't taught using python.

**Comment by nicholasjhorton** [comment]
For pandas, I'd suggest enumerating other key packages that users need to replicate the functionality of tidyverse within python.

**Comment by hardin47** [comment]
along with @nicholasjhorton good suggestions, i suggest that @hglanz  remove the part which directs to my entry (because my entry will follow).  thanks!

**Comment by hglanz** [comment]
Thank you both, @hardin47 @nicholasjhorton , for the comments. 

I'm coming up blank with ideas on how to do the code differently. Right now I'm only arriving at the following two ways to show off Python code:

1. the current way I have it (or in another Python IDE instead of Jupyter)
2. with the reticulate package as Jo's doing it in the next post

Only in the latter way will it not be through images. I agree that being able to copy the code is better than images, but as far as I can see right now it comes at the cost of demonstrating Jupyter more and "spoiling" the reticulate post. Let me know what you think.

I think the reticulate post is where the parallel Python and R code are displayed and I really like how @hardin47  has it right now. Let me know if you'd like to include it in the pandas post too.

I've added a section on "Teaching Data Science with Python" which really just includes information on other DS/Tidyverse packages in Python. @hardin47 wrote such a beautiful paragraph about "Teaching Python and R" and I didn't want to steal it....as much as I loved it and think it would fit.

I have now removed the reference to your post @hardin47 .

Sorry this one's coming down to the wire, but let me know if you have any more comments and I'll be sure to revise tomorrow (Sunday). I'm rebuilding tonight (Saturday), so feel free to check out the staging site.

**Comment by nicholasjhorton** [comment]
Images are fine with me.  I'd prefer to leave reticulate until Tuesday.  Can you add the jupyter notebook as a link at the end of the entry?

**Comment by hardin47** [comment]
i agree that images are fine, and i understand @hglanz point.

@nicholasjhorton   which link do you want added to which entry?  do you want the link to jupyter blog entry link to be in the reticulate entry?  or the pandas entry?  or do you want https://jupyter.org/ to be in the jupyter blog?

**Comment by hardin47** [comment]
i'm set on pandas (and clicked off my review check mark).  i'd say the only outstanding issue is the question about the link @nicholasjhorton wants to add.

**Comment by nicholasjhorton** [comment]
I just want to ensure that the pandas entry references the jupyter entry, and the reticulate entry references both pandas and jupyter.

**Comment by hardin47** [comment]
great!  i added a bunch of links here:  https://github.com/hglanz/DS-Blog-Ex/commit/66ff14fa89efca921f7946320c1eb8d452839b82

**Comment by hglanz** [comment]
Thanks all! It looks like all of the references/links have been added. I'm going with the post order on our wiki:

Monday: Jupyter
Tuesday: pandas
Wednesday: reticulate
Thursday: data8
Friday: Python Community

Please correct me if I'm wrong.

**Comment by nicholasjhorton** [comment]
This sentences feels awkward and tepid:

"Python has maintained great tools for data munging and preparation, the pandas library has helped Python take the next few steps in working well with data."

The first clause feels like a throwaway, and the second damning with faint praise.  Is that what you intended?  Can it be rewritten in a more positive way?

**Comment by hglanz** [comment]
I'm actually happy just taking that sentence out now that I look at it. Do you think it needs replacing or do you support just removing it?

**Comment by nicholasjhorton** [comment]
Eliding it works for me. 

All the best,

Nick
