### ISSUE TITLE
test pagination with ten entries vs five

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#81]
See https://github.com/hglanz/DS-Blog-Ex/commit/7952d84a265c07c829decce107da3339569d1d35 to address @hardin47's concerns about too many pages

**Comment by hardin47** [comment]
yay!!! any reason to stop at 10? I'd vote for 20 or 25 (or set it to 300 so that it doesn't ever limit). what do you think? thanks for finding @nicholasjhorton !!!

**Comment by hglanz** [comment]
So, I had known about this and I'm sorry I didn't bring it up earlier for your input. The default for the theme was 10, and I changed it to 5. I had thought we were going for more consolidation instead of a laundry-list of posts on the front page, but a lot is different from the previous theme besides this so I'm open :)

Just say the word....how many posts would you like per page? @nicholasjhorton @hardin47

**Comment by nicholasjhorton** [comment]
I'm happy with the status quo so am closing this for now.
