### ISSUE TITLE
cloud computing (AWS/Azure/GCP) post

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#82]
possible resource?  https://www.mikejohnpage.com/blog/returning-tweets-on-a-schedule-in-r-using-aws-ec2-rds-and-cron/

**Comment by nicholasjhorton** [comment]
also include Breiman's two cultures and CASI

**Comment by nicholasjhorton** [comment]
I've stubbed this out at https://github.com/hglanz/DS-Blog-Ex/tree/master/content/post/2019_07_31_Cloud2

Comments and suggestions welcomed.

**Comment by nicholasjhorton** [comment]
Note to @hglanz to avoid you having to authenticate I'd set eval = FALSE and echo = FALSE for the authentication and loading of the local data source (mostRevisions.Rda), respectively.  I'm cautiously optimistic that this will work but wanted to give you a heads up.

**Comment by nicholasjhorton** [comment]
The version on the staging site looks great.  Comments and suggestions welcomed on the content.

**Comment by hardin47** [comment]
I'm so excited about this entry, because it really pushes the boundaries of tools that I know and feel comfortable using!!!  Which means I have a lot of questions...

@nicholasjhorton I made some edits here: https://github.com/hglanz/DS-Blog-Ex/commit/8a3abcaa33529f6c79bd57661451257127376fa2   (feel free to change anything back, some of it was just style).

I have a few questions though.  

First of all, I'm a little bit confused about what you did.  Did you go to the cloud somehow?  Which line connected you to the cloud?  And what service did you use?  Can you spell out that step(s) for the user a little bit more?  I see that you are using R packages, but I don't understand how you connect in the cloud, how you pay for it, or what cloud service you are talking to.

And some wording questions:

1. You say "Gaining experience by investing some time in learning these tools will help ensure that students are using modern tools in their data science programs."  I'm not exactly sure who the subject of the sentence is.  That is, are you imploring teachers to get more experience?  Or students to get more experience?  I think the phrasing could be clarified in that way.

2. You say "the public dataset hosted in bigquery "  I don't really know what "bigquery" is.  I changed it to `bigquery` ...  but I don't know if that is right.  Maybe: [bigquery]()  to link somewhere?  Or is it just an R package, so `bigquery` is correct?

3. You say "All the work we perform is done in the database (and we are billed for it)."  What does it mean for the work to be done "in the database" ?

4. You say "## A shameless plus for CASI"  but I think you meant "## A shameless plug for CASI" ?  But you might have meant "plus".

**Comment by nicholasjhorton** [comment]
Kudos to @hardin47 for the excellent suggestions.  I've addressed them all here (but another read would be helpful).  See https://github.com/hglanz/DS-Blog-Ex/commit/61e112e4b46c8eb598aa041959b112ff12400731

**Comment by nicholasjhorton** [comment]
I've addressed another set of Jo's suggestions (and added a plug for the JSM).  But is the plug in the right place (MOnday's entry?). https://github.com/hglanz/DS-Blog-Ex/commit/b914385963a3d089eb2d29bd19e20b94a948f237

**Comment by hardin47** [comment]
so maybe this is enough for other people, but it wouldn't help me.  there isn't enough here for me to repeat the steps in the blog.  "I began by requesting GCP credits (see above) and used the online interface to create a project that I called "Test Project for Blog".   "  ...  i think "(see above)" refers to the different places where you can buy credits.  but that doesn't help me understand the following chunk.  i just don't understand how the items you've quoted will connect you to the cloud.  there isn't any information with a URL or folder path or anything.  but maybe that connection (i.e., what goes into those spots) would be obvious for someone else.

@hglanz -- have you done this before?  do you understand the connection to the cloud?   

i'm fine keeping it as is if the current incarnation is enough for other people.  i'm just trying to express that as a complete newbie, i wouldn't even know where to start.

```
projectId <- "bigquery-public-data"
billingId <- "test-project-for-blog" #replace with your own project
datasetName <- "samples"
tableName <- "wikipedia"
```

**Comment by hardin47** [comment]
@nicholasjhorton I have an idea!!!  Can you share with me the *actual* .Rmd file that you used?  And maybe I can read it to understand the process better and then make a suggestion for what we can say that would have helped me understand that chunk of R code above??  

Sorry to always be a pain in these situations ....

**Comment by nicholasjhorton** [comment]
I made some other light edits.  I'm going to go ahead and close this entry.

**Comment by nicholasjhorton** [comment]
Integrated suggestions from Laurie: https://github.com/hglanz/DS-Blog-Ex/commit/8467f5d4ae1cea3f69522887492b23d1729d1d41

**Comment by hglanz** [comment]
I have not done this before myself, but I also love this post. Thanks so much for both of your hard work, @nicholasjhorton @hardin47 . 

@hardin47 haven't seen you respond after seeing the .Rmd. Where do you stand on this now? 

On this, related, note....should we remind readers possibly in the closing thoughts entry that they can view the .Rmd files and other materials for the blog on the repo....and then link the repo? @nicholasjhorton @hardin47

**Comment by hardin47** [comment]
i'm all good with the cloud computing entry!  I'm going to respond about the closing in the other issue....
