### ISSUE TITLE
tidyeval: possible guest blog by Kelly Bodwin?

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#84]
I could imagine this file plus some pedagogical observations...

http://rpubs.com/kbodwin/tidy_eval

**Comment by hardin47** [comment]
i was very impressed by her insight.  i'd *love* to highlight it on the blog!!

**Comment by hglanz** [comment]
So I've been thinking about many of these types of things for a bit now because she and I are working on a couple of R packages this summer, and by "types of things" I mean these amazing, epiphany-like explanations she gets into. They're absolutely wonderful and I am super on-board with sharing them even more with the world.

My one, devil's advocate-type of thought right now is that tidyeval seems a bit niche for our blog. It's a very specific topic and the vibe I've had for our blog is more broad and shallow with the links and resources to dive deeper. Perhaps additionally, it feels niche pedagogically as well. She and I will be team-teaching an advanced R course here at Cal Poly next Spring and in light of this post of hers I asked how much tidyeval she thought we should include in the course.....it's still hard to say, but the initial thought is more introduction/awareness than heavy inclusion.

That being said I'd be more than happy to be convinced into finding a place for this on our blog :)

**Comment by nicholasjhorton** [comment]
Here's my take on why this is important.

Say a student needs to run a function over a set of variables (between 8-20 of them).  They don't grok purrr.  Or there is some reason why they can't use it.  All too often I'll see them repeat their code 20 times rather than iterate, since it's such a PITA to convert a string to a variable.  I'm thinking about a problem solving with iteration entry that might include the preferred purrr solution (I'm always happy to learn new things) and much of which she'd already written.

I would agree that a focus on NSE is less compelling, without a very specific use case.

Just my $0.02,

Nick

**Comment by hardin47** [comment]
as i said before, i, too, was very impressed by her insight.  she is able to break things down in ways that are incredibly illustrative.   however, i'm now finding myself more in Hunter's camp.  

if i were reading the blog as a way to start thinking about teaching data science (or trying to modernize my data science curriculum), i'd find that topic waaaaay in the weeds.  

if we could highlight it in some other way, it might be good.  for example, we might have a blog entry that listed rstudio webinars, rstudio cheatsheets, other data science blogs, asa communities / sections, something similar for CS prof orgs (?), ...  we could maybe highlight her musings in the body of the blog as an example of how we can all work together to get better.  maybe a blog on "the larger data science community" ?
